"""Add performance indexes

Revision ID: 7d332ad357b9
Revises: a1b2c3d4e5f6
Create Date: 2026-07-12 13:25:14.103074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d332ad357b9'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_courses_mentor_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_status_deleted'), table_name='courses')
    op.create_index('idx_courses_mentor_active', 'courses', ['mentor_id'], unique=False, postgresql_where=sa.text("status = 'active' AND is_deleted = false"))
    op.drop_index(op.f('ix_enrollments_course_student_deleted'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_student_deleted'), table_name='enrollments')
    op.drop_index(op.f('ix_journal_entries_journal_student'), table_name='journal_entries')
    op.create_index('idx_journal_entries_student_attendance', 'journal_entries', ['student_id'], unique=False, postgresql_where=sa.text('attendance = false'))
    op.drop_index(op.f('ix_journal_student_summary_journal_student'), table_name='journal_student_summaries')
    op.drop_index(op.f('ix_notification_logs_idempotency'), table_name='notification_logs')
    op.drop_index(op.f('ix_payments_paid_at'), table_name='payments')
    op.drop_index(op.f('ix_payments_student_course'), table_name='payments')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_payments_student_course'), 'payments', ['student_id', 'course_id'], unique=False)
    op.create_index(op.f('ix_payments_paid_at'), 'payments', ['paid_at'], unique=False)
    op.create_index(op.f('ix_notification_logs_idempotency'), 'notification_logs', ['recipient', 'type', 'related_entity_id', 'notification_date'], unique=True)
    op.create_index(op.f('ix_journal_student_summary_journal_student'), 'journal_student_summaries', ['journal_id', 'student_id'], unique=True)
    op.drop_index('idx_journal_entries_student_attendance', table_name='journal_entries', postgresql_where=sa.text('attendance = false'))
    op.create_index(op.f('ix_journal_entries_journal_student'), 'journal_entries', ['journal_id', 'student_id'], unique=False)
    op.create_index(op.f('ix_enrollments_student_deleted'), 'enrollments', ['student_id', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_enrollments_course_student_deleted'), 'enrollments', ['course_id', 'student_id', 'is_deleted'], unique=False)
    op.drop_index('idx_courses_mentor_active', table_name='courses', postgresql_where=sa.text("status = 'active' AND is_deleted = false"))
    op.create_index(op.f('ix_courses_status_deleted'), 'courses', ['status', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_courses_mentor_id'), 'courses', ['mentor_id'], unique=False)
    # ### end Alembic commands ###
